### ISSUE TITLE
how to compare repertoires

### ISSUE THREAD

**Issue by vanessajmh** [statbiophys/soNNia#2]
Hello,
Is it currently possible to compare repertoires using the JSD function implemented in your pipeline?
I see that you have a method to compute it however I can't seem to find any explanation on how to use it.
Thanks!

**Comment by giulioisac** [comment]
Hello,
thanks for the question. I haven't written the documentation for that part yet but if you send me an email at giulioisac@gmail.com with an explanation of what you want to do, I can help you with it.
Best,
Giulio
